//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HermesDBEntities : DbContext
    {
        public HermesDBEntities()
            : base("name=HermesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CustomPreSlaExpirationNotificationsTable> CustomPreSlaExpirationNotificationsTables { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<HistoryAction> HistoryActions { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationsType> NotificationsTypes { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Retailer> Retailers { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Solutionist> Solutionists { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TicketType> TicketTypes { get; set; }
        public virtual DbSet<TravelContract> TravelContracts { get; set; }
        public virtual DbSet<TravelDestination> TravelDestinations { get; set; }
        public virtual DbSet<TravelEvent> TravelEvents { get; set; }
        public virtual DbSet<TravelRegion> TravelRegions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<Workstation> Workstations { get; set; }
    }
}
