//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public int userId { get; set; }
        public Nullable<int> dealerId { get; set; }
        public Nullable<int> wsId { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string adress { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> contactId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual User User { get; set; }
        public virtual Workstation Workstation { get; set; }
    }
}
