//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelContract
    {
        public int Id { get; set; }
        public int TravelEventId { get; set; }
        public int Quantity { get; set; }
        public string Adress { get; set; }
        public string NameOfClient { get; set; }
        public int GroupId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual TravelEvent TravelEvent { get; set; }
    }
}
