//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelDestination
    {
        public TravelDestination()
        {
            this.TravelEvents = new HashSet<TravelEvent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TravelRegionId { get; set; }
    
        public virtual TravelRegion TravelRegion { get; set; }
        public virtual ICollection<TravelEvent> TravelEvents { get; set; }
    }
}
