//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int id { get; set; }
        public int ticketId { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<bool> isVisible { get; set; }
        public Nullable<int> uploader_id { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
