//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomPreSlaExpirationNotificationsTable
    {
        public int Id { get; set; }
        public int userSettingsId { get; set; }
        public int minutesBeforeSlaExpires { get; set; }
        public int notificationTypeId { get; set; }
    
        public virtual Setting Setting { get; set; }
    }
}
