//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Reports = new HashSet<Report>();
            this.TravelContracts = new HashSet<TravelContract>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte level { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<TravelContract> TravelContracts { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
