//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int OwnerId { get; set; }
        public int CreatorId { get; set; }
        public int NotificationTypeId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> TicketId { get; set; }
        public bool Readed { get; set; }
    
        public virtual User User { get; set; }
        public virtual NotificationsType NotificationsType { get; set; }
        public virtual User User1 { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
