//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int id { get; set; }
        public int categoryId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string garant { get; set; }
        public string supplier { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
