//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public Setting()
        {
            this.CustomPreSlaExpirationNotificationsTables = new HashSet<CustomPreSlaExpirationNotificationsTable>();
        }
    
        public int userId { get; set; }
        public bool emailNotification { get; set; }
        public bool regularEmailsNotification { get; set; }
    
        public virtual ICollection<CustomPreSlaExpirationNotificationsTable> CustomPreSlaExpirationNotificationsTables { get; set; }
        public virtual User User { get; set; }
    }
}
