//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSla
    {
        public int ticketId { get; set; }
        public Nullable<System.DateTime> startAt { get; set; }
        public Nullable<System.DateTime> RT_expiresAt { get; set; }
        public Nullable<System.DateTime> RT_realCompletedAt { get; set; }
        public Nullable<System.DateTime> FT_expiresAt { get; set; }
        public Nullable<System.DateTime> FT_realCompletedAt { get; set; }
        public Nullable<System.DateTime> FT_fakeCompletedAt { get; set; }
        public Nullable<int> FT_remainingSec { get; set; }
        public Nullable<System.DateTime> FT3lvl_expiresAt { get; set; }
        public Nullable<System.DateTime> FT3lvl_realCompletedAt { get; set; }
        public Nullable<System.DateTime> FT3lvl_fakeCompletedAt { get; set; }
        public Nullable<int> FT3lvl_remainingSec { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
