//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHistory
    {
        public int Id { get; set; }
        public int ticketId { get; set; }
        public int userId { get; set; }
        public int actionId { get; set; }
        public System.DateTime date { get; set; }
        public string text { get; set; }
        public string reason { get; set; }
    
        public virtual HistoryAction HistoryAction { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
