//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public string ticketId { get; set; }
        public int authorId { get; set; }
        public int createdByUserId { get; set; }
        public Nullable<int> solutionistId { get; set; }
        public Nullable<int> groupId { get; set; }
        public int statusId { get; set; }
        public Nullable<int> productId { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public System.DateTime createdAt { get; set; }
        public Nullable<System.DateTime> completedAt { get; set; }
        public Nullable<int> typeId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
