//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
            this.Tickets = new HashSet<Ticket>();
            this.Tickets1 = new HashSet<Ticket>();
            this.Tickets2 = new HashSet<Ticket>();
            this.Groups = new HashSet<Group>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int regionId { get; set; }
        public string profilePictureUrl { get; set; }
        public bool isSolutionist { get; set; }
        public bool isSystem { get; set; }
        public Nullable<bool> isPasswordConfirmed { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Notification> Notifications1 { get; set; }
        public virtual Region Region { get; set; }
        public virtual Retailer Retailer { get; set; }
        public virtual Setting Setting { get; set; }
        public virtual Solutionist Solutionist { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Ticket> Tickets1 { get; set; }
        public virtual ICollection<Ticket> Tickets2 { get; set; }
        public virtual webpages_Membership webpages_Membership { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
